import Link from "next/link";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <nav>
          <ul>
            <li>
              <Link href={"/server"}>/server</Link>
            </li>
            <li>
              <Link href={"/client"}>/client</Link>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
