import Link from "next/link";
import "./globals.css";

export const metadata = {
  title: {
    default: "Next.js | Jungyu",
    template: "%s | Jungyu",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <nav>
          <ul>
            <li>
              <Link href="/about">/about</Link>
            </li>
            <li>
              <Link href="/blog">/blog</Link>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
